### ISSUE TITLE
Use PubMedCLIP as a pretrained model

### ISSUE THREAD

**Issue by hajihosseini** [sarahESL/PubMedCLIP#14]
Hello. Thank you for this research.
I have a question about this work. I try to use PubMedCLIP as a pretrained model for extracting features from medical images and questions but I can't. Can you help me to solve this problem? How can I use this model as a pretrained model?
Thanks

**Comment by sarahESL** [comment]
Thanks for your interest in our work.
Lines 138 to 143 in https://github.com/sarahESL/PubMedCLIP/blob/main/QCR_PubMedCLIP/lib/BAN/multi_level_model.py shows an example of how you can load the pre-trained PubmedCLIP models. 
Once the model is loaded, you can simply encode your images by `model.encode_image(image)`, similar to what described in the README at https://github.com/openai/CLIP .

**Comment by hajihosseini** [comment]
Thank you for the response.
