### ISSUE TITLE
imgid2idx.json

### ISSUE THREAD

**Issue by Zhaihanlei** [sarahESL/PubMedCLIP#16]
How is imgid2idx.json generated

**Comment by sarahESL** [comment]
You can use this script from this repo: [https://github.com/sarahESL/PubMedCLIP/blob/main/QCR_PubMedCLIP/lib/utils/create_img2idx.py](https://github.com/sarahESL/PubMedCLIP/blob/main/QCR_PubMedCLIP/lib/utils/create_img2idx.py
)
