### ISSUE TITLE
pretrained_ae.pth

### ISSUE THREAD

**Issue by Zhaihanlei** [sarahESL/PubMedCLIP#17]
How to find the two files pretrained_ae.pth and pretrained_maml.pth, thank you for telling me

**Comment by Zhaihanlei** [comment]
and this files pretrained_maml.weights

**Comment by sarahESL** [comment]
The weights are directly taken from previous work: [https://github.com/Awenbocc/med-vqa/tree/master/data](https://github.com/Awenbocc/med-vqa/tree/master/data)
