### ISSUE TITLE
Unable to access pretrained models on OneDrive

### ISSUE THREAD

**Issue by Hadlay-Zhang** [sarahESL/PubMedCLIP#21]
Hi, 
Thanks for your contribution and code sharing. Unfortunately, I can't download the pretrained models from OneDrive as the link appears to be broken or restricted.

Could you please check the link and provide an alternative if possible?

Thank you!

**Comment by sarahESL** [comment]
Hello,

The OneDrive link is still functioning.

Nevertheless, I pushed the checkpoints to HuggingFace as well and you can download them from there, too:

[https://huggingface.co/sarahESL/PubMedCLIP](https://huggingface.co/sarahESL/PubMedCLIP)

Let me know if you still cannot access the checkpoints.

**Comment by Hadlay-Zhang** [comment]
> Hello,
> 
> The OneDrive link is still functioning.
> 
> Nevertheless, I pushed the checkpoints to HuggingFace as well and you can download them from there, too:
> 
> https://huggingface.co/sarahESL/PubMedCLIP
> 
> Let me know if you still cannot access the checkpoints.

HF works for me. Thanks a lot.
