### ISSUE TITLE
Issues with lib/utils/run.sh for input files

### ISSUE THREAD

**Issue by zyzkevin** [sarahESL/PubMedCLIP#3]
Hello, 
I'm having trouble running the script for generating the input files (dictionaries, and pickles). One problem in lib/utils/run.sh runs python create_dictionary.py "../../data/data_slake" instead of /data_rad/. However, after changing the directory to data_rad more issues pop up including df columns not matching and I understand that most likely the file was not modified perfectly for generating both datasets' inputs.

It took a while to get them all working, but it would be nice to see a fix.

**Comment by sarahESL** [comment]
Thanks for the comment and opening the issue. I will have a look as soon as I get the time. Meanwhile, feel free to make a pull request with your changes if you want.

**Comment by lycutter** [comment]
> Hello, I'm having trouble running the script for generating the input files (dictionaries, and pickles). One problem in lib/utils/run.sh runs python create_dictionary.py "../../data/data_slake" instead of /data_rad/. However, after changing the directory to data_rad more issues pop up including df columns not matching and I understand that most likely the file was not modified perfectly for generating both datasets' inputs.
> 
> It took a while to get them all working, but it would be nice to see a fix.

Hello, 
Could you please share the preprocess data on data_rad, I found some troubles in generating the files. Thanks!

**Comment by sarahESL** [comment]
Thanks @lycutter and @zyzkevin for reporting this issue. 

Both `create_dictionary.py` and `create_label.py` should be fixed now and work for both `VQA_RAD` and `VQA_SLAKE` datasets. 

Let me know if any other issues shall arise!

**Comment by lycutter** [comment]
> Thanks @lycutter and @zyzkevin for reporting this issue.
> 
> Both `create_dictionary.py` and `create_label.py` should be fixed now and work for both `VQA_RAD` and `VQA_SLAKE` datasets.
> 
> Let me know if any other issues shall arise!
Thank for your replying, I update these two files and use them to generate the input files. However, it occured some bugs too, suah as key error 'answer[image_name] ' in the data_RAD.py, dimension mismatch when loading the type_classifer.pth. The train.json file and test.json file I use are from https://github.com/aioz-ai/MICCAI19-MedVQA. I don't know whether these bugs are related to these two .json files. Could you plz share all the completed input files.
Thanks!

**Comment by sarahESL** [comment]
@lycutter The scripts in this repo should work for the official datasets released in the original `VQA_RAD` paper. But maybe you can use the data from https://github.com/Awenbocc/med-vqa/tree/master/data?

If the error in ` data_RAD.py` still appears, I would appreciate it if you could make another issue and write the error you get there. Let's keep this thread for issues arising from `lib/utils/run.sh`.

**Comment by lycutter** [comment]
> @lycutter The scripts in this repo should work for the official datasets released in the original `VQA_RAD` paper. But maybe you can use the data from https://github.com/Awenbocc/med-vqa/tree/master/data?
> 
> If the error in ` data_RAD.py` still appears, I would appreciate it if you could make another issue and write the error you get there. Let's keep this thread for issues arising from `lib/utils/run.sh`.

Thanks for your help! It works now.
